### PR TITLE
add additional resources for chdev, multibos, no

### PR DESCRIPTION
**Pull request by chmod666org**
Adding resources for chdev, multibos, no
README.md changed with documentation for new providers

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chmod666org** [comment]
ICLA signed and supermarket account linked to my github accound

**Comment by chmod666org** [comment]
Adding resources and providers for chsec

**Comment by juliandunn** [comment]
Nice work overall, @chmod666org! I trust you with this & am pretty ready to merge :-) my only remark is that could we log at debug level instead of info for all the debugging messages.

**Comment by chmod666org** [comment]
Ohai @juliandunn !
Yes, you are right, will change all the messages to debug.
Going also to add nimclient lwrp. Will commit asap.

**Comment by chmod666org** [comment]
Hi @juliandunn I have change all the info to debug. Just add huge lwrp for niminit/nimclient
Needs to change the README for documentation. Do you need it updated for merge ?
Regards,
B.

**Comment by juliandunn** [comment]
@chmod666org yes do you mind writing a few things about that LWRP since I am not 100% familiar with using NIM.

**Comment by chmod666org** [comment]
@juliandunn ok will do this asap.

**Comment by chmod666org** [comment]
README.md changed. Tell me if it ok.

**Comment by juliandunn** [comment]
Generally it looks fine, thanks @chmod666org. I will edit it a bit for copy but thanks!

**Comment by chmod666org** [comment]
Ok @juliandunn thank you for your time. Feel free to make any changes. There are still lot of things to do for this AIX cookbook. Can I add issues to tell what is needed. Some of my friends wants to participate but they don't know exactly what is needed, so I think putting all required lwrp in the issues (like you have already done for wpar and rmssys/mkssys) can guide people who wants to participate. What do you think about it?

**Comment by juliandunn** [comment]
@chmod666org yes that would be great if you could add issues for things you feel are necessary. I am not an AIX expert so I don't know what people want to do on this platform!

**Comment by chmod666org** [comment]
OK. I am :-). Really want to spread the word about Chef and AIX. We need an automation tool on AIX, trying to do my best to push things forward on AIX with Chef. The more we do here the better chance we will have to see chef adopted by the community. So let's do this. My goal here is to automate updates and post installations task with chef. Working on alt_disks, mksysb, emgr management with Chef now. Couple of LWRP will come in the next weeks. Love Chef \o/

**Comment by juliandunn** [comment]
Amazing, thank you again for the contribution @chmod666org and look forward to more.

**Pull request merged**
